import { ReviewCard } from './components/ReviewCard';
import { SectionTitle } from '../SectionTitle';

import courtney from './assets/courtney.png';
import mckinney from './assets/mckinney.png';
import roselle from './assets/roselle.png';
import floyd from './assets/floyd.png';
import lauralee from './assets/lauralee.png';
import kylee from './assets/kylee.png';
import tyra from './assets/tyra.png';
import marx from './assets/marx.png';

export function ReviewSection() {
  return (
    <section className="flex py-24 px-20 flex-col justify-center items-center gap-12">
      <SectionTitle
        title="Used by More Than 10K+ Business"
        subtitle="Hear what they say about Venture and why you should choose Venture"
      />

      <div className="grid grid-cols-2 w-full gap-6">
        <ReviewCard
          authorImageSrc={courtney}
          authorName="Courtney H."
          authorTitle="UI/UX Designer"
          reviewDescription="I was looking for a CRM that was easy to use and could adapt to my business. This CRM has exceeded my expectations. It's simple, intuitive, and customizable."
        />
        <ReviewCard
          authorImageSrc={mckinney}
          authorName="M. McKinney"
          authorTitle="Team Leader"
          reviewDescription="The sales pipeline and automation tools have been a massive time-saver. We can now manage leads and deals more efficiently, which has had a direct impact on our bottom line."
        />
        <ReviewCard
          authorImageSrc={roselle}
          authorName="Roselle Ehrman"
          authorTitle="Software Developer"
          reviewDescription="The reports generated by this CRM have allowed us to track and measure our performance better than ever. It's helped us identify areas for improvement and growth opportunities."
        />
        <ReviewCard
          authorImageSrc={floyd}
          authorName="Floyd Miles"
          authorTitle="Software Manager"
          reviewDescription="The ability to segment customers and personalize our marketing campaigns has led to a significant increase in conversion rates. It's been a game-changer for our e-commerce business."
        />
        <ReviewCard
          authorImageSrc={lauralee}
          authorName="Lauralee Q."
          authorTitle="Scrum Master"
          reviewDescription="Our customer support has become more organized and efficient with this CRM. The ticketing system and knowledge base features have made a significant difference in how we serve our customers."
        />
        <ReviewCard
          authorImageSrc={kylee}
          authorName="Kylee Danford"
          authorTitle="Ethical Hacker"
          reviewDescription="The collaboration features in this CRM have greatly improved how our teams work together. Sharing information and coordinating has never been easier."
        />
        <ReviewCard
          authorImageSrc={tyra}
          authorName="Tyra Dhillon"
          authorTitle="Software Tester"
          reviewDescription="This CRM seamlessly integrated with our existing systems. The implementation was a breeze, and it's made a significant difference in our data management."
        />
        <ReviewCard
          authorImageSrc={marx}
          authorName="Marx Hershey"
          authorTitle="Project Manager"
          reviewDescription="Since implementing this CRM, our sales have increased by 30% in just three months. It's become an integral part of our growth strategy."
        />
      </div>
    </section>
  );
}
