export const uiRoutes = {
  public: {
    index: '/',
    about: '/about',
    features: '/features',
    pricing: '/pricing',
    blog: '/blog',
    login: '/login',
    signup: '/signup',
    newPassword: '/new-password',
    resetPassword: '/reset-password',
  },
  auth: {
    index: '/auth',
    dashboard: '/auth/dashboard',
    notifications: '/auth/notifications',
    notes: '/auth/notes',
    tasks: '/auth/tasks',
    emails: '/auth/emails',
    calendars: '/auth/calendars',
    analytics: '/auth/analytics',
    contacts: '/auth/contacts',
    companies: '/auth/companies',
    integrations: '/auth/integrations',
    settings: '/auth/settings',
    helpCenter: '/auth/help-center',
  },
} as const;
